[2021-06-27 20:04:27,969] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: mysqltomongo.import_mysql_customer 2021-06-25T00:00:00+00:00 [queued]>
[2021-06-27 20:04:28,110] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: mysqltomongo.import_mysql_customer 2021-06-25T00:00:00+00:00 [queued]>
[2021-06-27 20:04:28,111] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 20:04:28,112] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-06-27 20:04:28,131] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-27 20:04:28,257] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): import_mysql_customer> on 2021-06-25T00:00:00+00:00
[2021-06-27 20:04:28,326] {standard_task_runner.py:52} INFO - Started process 1809 to run task
[2021-06-27 20:04:28,441] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'mysqltomongo', 'import_mysql_customer', '2021-06-25T00:00:00+00:00', '--job-id', '101', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/sqlMongo.py', '--cfg-path', '/tmp/tmpzaid38ea', '--error-file', '/tmp/tmpxne8_vji']
[2021-06-27 20:04:28,454] {standard_task_runner.py:77} INFO - Job 101: Subtask import_mysql_customer
[2021-06-27 20:04:28,965] {logging_mixin.py:104} INFO - Running <TaskInstance: mysqltomongo.import_mysql_customer 2021-06-25T00:00:00+00:00 [running]> on host b69deda3a989
[2021-06-27 20:04:29,928] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=tech@innospark.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mysqltomongo
AIRFLOW_CTX_TASK_ID=import_mysql_customer
AIRFLOW_CTX_EXECUTION_DATE=2021-06-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-25T00:00:00+00:00
[2021-06-27 20:04:29,932] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sqlMongo.py", line 26, in mysql_bulk_load_mongo
    conn = MongoHook(mysql_conn_id=kwargs['conn_id'])
NameError: name 'MongoHook' is not defined
[2021-06-27 20:04:29,953] {taskinstance.py:1531} INFO - Marking task as UP_FOR_RETRY. dag_id=mysqltomongo, task_id=import_mysql_customer, execution_date=20210625T000000, start_date=20210627T200427, end_date=20210627T200429
[2021-06-27 20:04:30,275] {local_task_job.py:151} INFO - Task exited with return code 1
